forcedotcom/npm-release-management-orb

- README.md
- src/@orb.yml
- src/commands/install-sfdx-trust.yml
- src/commands/install-sfdx.yml
- src/commands/setup-aws.yml
- src/commands/sign-and-publish.yml
- src/examples/test-and-release.yml
- src/executors/default.yml
- src/jobs/release-package.yml
- src/jobs/test-package.yml
> Add functionality for testing and releasing packages

- README.md
- src/commands/create-git-tag.yml
- src/commands/install-sfdx-trust.yml
- src/commands/publish.yml
- src/commands/setup-aws.yml
- src/commands/sign-and-publish.yml
- src/commands/validate-release-version.yml
- src/examples/test-and-release.yml
- src/jobs/release-package.yml
- src/jobs/release-signed-package.yml
- add env var reference and getting started steps to README
- check for existing version at the beginning of release jobs
- add functionality for creating git tags
> Improve the orb

- .circleci/config.yml
- src/commands/sign.yml
- src/commands/verify-fingerprint.yml
@W-7912363@
Depends on https://git.soma.salesforce.com/salesforcedx/sfdx-trust/pull/27 being released first
Also, people will need to opt-in to receiving email notifications for build failures. So either we need get everyone on the team to opt-in OR we could possibly setup an account in Circle that uses the team email
> Add verify-fingerprint command

- src/jobs/test-ts-update.yml
Adds job to run tests against latest typescript and ES target
@W-8667963@
> add test-ts-update.yml

- README.md
Added a env var, NPM_REGISTRY, that allows users to select which npm
registry is to be used for install and publish actions.
> feat: 🎸 @W-8712470@ add env var for target registry

- src/examples/test-and-release-package-all-branches.yml
- src/examples/test-and-release-package-beta-version.yml
- src/jobs/release-package.yml
- src/jobs/validate-pr.yml
fix: validate-pr to check PR title and message
fix: update cache to include local node_modules
fix: update cache key to not include circleci config
> feat: add prerelease

- src/jobs/release-lerna-packages.yml
previous CTC commit didn't modify the lerna version of release-package.  This one does.
> feat: CTC on lerna, too!

- src/commands/install-node.yml
@W-8827814@
* Fix typo, oops.
* Update NVM on CircleCI so we don't rely on whatever (outdated) version they give us.
> [semver:minor] update NVM in orb

- .idea/workspace.xml
- src/examples/test-and-release-package-all-branches.yml
- src/examples/test-and-release-package-beta-version.yml
- src/examples/test-and-release-package-with-merge.yml
- src/examples/test-and-release-package.yml
- src/examples/test-and-release-signed-plugin.yml
- src/jobs/release-lerna-packages.yml
- src/jobs/release-package.yml
- src/jobs/test-nut.yml
- src/jobs/test-package.yml
> feat: add run all nuts

- src/jobs/release-lerna-packages.yml
- src/jobs/release-package.yml
- src/jobs/test-nut.yml
- src/jobs/test-package.yml
> chore: correct branch name reference for cache keys

- src/commands/install-node.yml
Properly install new version of `nvm` so that version changes work
@W-9120044@
> fix install-node

- src/jobs/test-nut.yml
> feat: add param npm_module_name to test-nut

- src/jobs/test-nut.yml
> [semver:patch] chore: condition checkout for each platform

- src/jobs/test-nut.yml
- src/jobs/test-package.yml
Default node version to latest
@W-9160953@
> feat: default node version to latest

- src/@orb.yml
- src/commands/upload-coverage.yml
Removes codecov report and upload
@W-9228425@
> chore: remove codecov commands and orbs

- src/commands/install-node.yml
comments out the node version modifications for windows
> fix: use circle image default node version

- src/commands/install-sf-release.yml
this seems to work in local bash.  Circle is a strange place sometimes...please verify this will do what I think it does.
> feat: env sets plugin-rel-mgmt version

- src/commands/install-sfdx.yml
Removes the install script and instead add bin to the $PATH
@W-9830954@
> fix: dont use the install script instead add bin to path

- src/commands/halt-workflow-if-not-releasable.yml
> Use --json for checking if release is required

- src/commands/install-node.yml
@W-10512203@
see linked PR https://github.com/salesforcecli/plugin-auth/pull/360 for QA
> [semver:minor] use windows node lts, not latest

- .circleci/config.yml
use a project level CIRCLE_TOKEN
@W-0@
> fix: use project level circle token for publishing
